# Generated by Django 5.2.3 on 2025-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('note_num', models.IntegerField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dere_st', models.IntegerField(choices=[(1, 'Demo Version'), (2, 'Released Version')], default=1)),
                ('privaty_ch', models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=2)),
            ],
        ),
    ]
